services:
  stats-server:
    build:
      context: .
      dockerfile: stats-service/stats-server/Dockerfile
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-stats
#      - SPRING_DATASOURCE_USERNAME=stat
#      - SPRING_DATASOURCE_PASSWORD=stat

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats

  ewm-service:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    container_name: ewm-server
    ports:
      - "8080:8080"
#    environment:
#      - CLIENT_URL=http://stats-server:9090
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
#      - SPRING_DATASOURCE_USERNAME=main
#      - SPRING_DATASOURCE_PASSWORD=main
